(function(){
  const STORAGE_KEY="nextpoint_language";
  const LANGS={
    it:{flag:"🇮🇹",flagCode:"it",short:"IT",name:"Italiano",dir:"ltr"},
    en:{flag:"🇺🇸",flagCode:"us",short:"EN",name:"English",dir:"ltr"},
    fr:{flag:"🇫🇷",flagCode:"fr",short:"FR",name:"Français",dir:"ltr"},
    es:{flag:"🇪🇸",flagCode:"es",short:"ES",name:"Español",dir:"ltr"},
    de:{flag:"🇩🇪",flagCode:"de",short:"DE",name:"Deutsch",dir:"ltr"}
  };
  const TEXT={
  "it": {
    "brandSub": "Tornei • Eventi • Competizioni di padel",
    "access": "Accesso utenti",
    "emailLabel": "Email",
    "emailPlaceholder": "Inserisci la tua email",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Inserisci la tua password",
    "remember": "Ricordami",
    "forgot": "Password dimenticata?",
    "login": "ACCEDI",
    "register": "REGISTRATI",
    "notRegistered": "Non sei iscritto?",
    "registerLink": "Registrati",
    "enterCredentials": "Inserisci email e password",
    "registering": "Registrazione in corso...",
    "registered": "Registrazione completata. Ora puoi accedere.",
    "accessing": "Accesso in corso...",
    "resetSending": "Invio richiesta reset password...",
    "resetSent": "Controlla la tua email per reimpostare la password",
    "enterEmail": "Inserisci prima la tua email",
    "language": "Lingua"
  },
  "en": {
    "brandSub": "Tournaments • Events • Padel competitions",
    "access": "User login",
    "emailLabel": "Email",
    "emailPlaceholder": "Enter your email",
    "passwordLabel": "Password",
    "passwordPlaceholder": "Enter your password",
    "remember": "Remember me",
    "forgot": "Forgot password?",
    "login": "LOGIN",
    "register": "REGISTER",
    "notRegistered": "Not registered?",
    "registerLink": "Register",
    "enterCredentials": "Enter email and password",
    "registering": "Registration in progress...",
    "registered": "Registration completed. You can now log in.",
    "accessing": "Signing in...",
    "resetSending": "Sending password reset request...",
    "resetSent": "Check your email to reset your password",
    "enterEmail": "Enter your email first",
    "language": "Language"
  },
  "fr": {
    "brandSub": "Tournois • Événements • Compétitions de padel",
    "access": "Accès utilisateurs",
    "emailLabel": "E-mail",
    "emailPlaceholder": "Saisissez votre e-mail",
    "passwordLabel": "Mot de passe",
    "passwordPlaceholder": "Saisissez votre mot de passe",
    "remember": "Se souvenir de moi",
    "forgot": "Mot de passe oublié ?",
    "login": "SE CONNECTER",
    "register": "S’INSCRIRE",
    "notRegistered": "Pas encore inscrit ?",
    "registerLink": "Inscrivez-vous",
    "enterCredentials": "Saisissez votre e-mail et votre mot de passe",
    "registering": "Inscription en cours...",
    "registered": "Inscription terminée. Vous pouvez maintenant vous connecter.",
    "accessing": "Connexion en cours...",
    "resetSending": "Envoi de la demande de réinitialisation...",
    "resetSent": "Consultez votre e-mail pour réinitialiser votre mot de passe",
    "enterEmail": "Saisissez d’abord votre e-mail",
    "language": "Langue"
  },
  "es": {
    "brandSub": "Torneos • Eventos • Competiciones de pádel",
    "access": "Acceso de usuarios",
    "emailLabel": "Correo electrónico",
    "emailPlaceholder": "Introduce tu correo electrónico",
    "passwordLabel": "Contraseña",
    "passwordPlaceholder": "Introduce tu contraseña",
    "remember": "Recordarme",
    "forgot": "¿Has olvidado la contraseña?",
    "login": "ACCEDER",
    "register": "REGISTRARSE",
    "notRegistered": "¿No estás registrado?",
    "registerLink": "Regístrate",
    "enterCredentials": "Introduce el correo electrónico y la contraseña",
    "registering": "Registrando...",
    "registered": "Registro completado. Ya puedes acceder.",
    "accessing": "Iniciando sesión...",
    "resetSending": "Enviando solicitud para restablecer la contraseña...",
    "resetSent": "Revisa tu correo electrónico para restablecer la contraseña",
    "enterEmail": "Introduce primero tu correo electrónico",
    "language": "Idioma"
  },
  "de": {
    "brandSub": "Turniere • Veranstaltungen • Padel-Wettbewerbe",
    "access": "Benutzerzugang",
    "emailLabel": "E-Mail",
    "emailPlaceholder": "E-Mail-Adresse eingeben",
    "passwordLabel": "Passwort",
    "passwordPlaceholder": "Passwort eingeben",
    "remember": "Angemeldet bleiben",
    "forgot": "Passwort vergessen?",
    "login": "ANMELDEN",
    "register": "REGISTRIEREN",
    "notRegistered": "Noch nicht registriert?",
    "registerLink": "Registrieren",
    "enterCredentials": "E-Mail und Passwort eingeben",
    "registering": "Registrierung läuft...",
    "registered": "Registrierung abgeschlossen. Sie können sich jetzt anmelden.",
    "accessing": "Anmeldung läuft...",
    "resetSending": "Anfrage zum Zurücksetzen des Passworts wird gesendet...",
    "resetSent": "Prüfen Sie Ihre E-Mail, um das Passwort zurückzusetzen",
    "enterEmail": "Geben Sie zuerst Ihre E-Mail-Adresse ein",
    "language": "Sprache"
  }
};
  const LANDING_TEXT={
  "it": {
    "pageTitle": "Next Point Padel — La piattaforma digitale per il tuo club",
    "navPlatform": "Piattaforma",
    "navHow": "Come funziona",
    "navSociety": "Società",
    "activate": "ATTIVA IL TUO CLUB",
    "heroEyebrow": "La piattaforma digitale per il padel",
    "heroTitle": "Il tuo club.<br>Una nuova esperienza digitale.",
    "heroLead": "Next Point Padel aiuta le società a gestire tornei, giocatori, eventi e comunicazione in un unico ambiente professionale.",
    "discover": "SCOPRI LA PIATTAFORMA",
    "heroNote": "Pensata per società, circoli e organizzatori di padel.",
    "introKicker": "Più controllo. Meno lavoro.",
    "introTitle": "Il club che vuoi gestire, in un solo posto.",
    "introText": "Una piattaforma pensata per semplificare la gestione quotidiana e offrire ai tuoi giocatori un'esperienza digitale moderna. Tornei, risultati, eventi e comunicazioni fanno parte dello stesso ecosistema.",
    "featureTournaments": "Tornei",
    "featureTournamentsText": "Organizza formule, gironi, tabelloni, risultati e classifiche.",
    "featurePlayers": "Giocatori",
    "featurePlayersText": "Gestisci iscrizioni, partecipanti e accessi all'ambiente del club.",
    "featureNews": "Eventi & News",
    "featureNewsText": "Comunica iniziative, appuntamenti e contenuti direttamente ai tuoi utenti.",
    "featureIdentity": "Identità del club",
    "featureIdentityText": "Uno spazio digitale costruito intorno alla tua società e al tuo pubblico.",
    "darkKicker": "Dal caos all'organizzazione",
    "darkTitle": "Meno strumenti separati. Più tempo per il tuo club.",
    "darkText": "Fogli, messaggi, iscrizioni, risultati e comunicazioni non devono vivere in posti diversi. Next Point Padel riunisce le attività principali del club in un'esperienza coordinata e semplice da utilizzare.",
    "seeHow": "VEDI COME FUNZIONA",
    "solutionKicker": "Cosa puoi fare",
    "solutionTitle": "Una piattaforma costruita per il club.",
    "solutionText": "Non un semplice elenco di funzioni: un ambiente digitale che accompagna la società dalla gestione interna all'esperienza del giocatore.",
    "management": "Gestione",
    "organizeTournaments": "Organizza i tornei",
    "organizeTournamentsText": "Crea e gestisci competizioni, formule, squadre, partite, risultati e classifiche.",
    "communication": "Comunicazione",
    "beVisible": "Fatti vedere",
    "beVisibleText": "News, eventi e contenuti aiutano il club a mantenere attiva la relazione con i propri giocatori.",
    "experience": "Esperienza",
    "engagePlayers": "Coinvolgi i giocatori",
    "engagePlayersText": "Un accesso digitale semplice per scoprire tornei, attività, risultati e servizi della società.",
    "showcaseKicker": "Un ecosistema, non un semplice gestionale",
    "showcaseTitle": "La tecnologia lavora dietro le quinte. Il club resta protagonista.",
    "showcaseTournaments": "Tornei e competizioni",
    "showcaseTournamentsText": "Dalla creazione della competizione alla gestione dei risultati e del tabellone.",
    "showcaseCommunication": "Comunicazione del club",
    "showcaseCommunicationText": "News, eventi e contenuti in un ambiente coerente con la società.",
    "showcaseAccess": "Accesso per i giocatori",
    "showcaseAccessText": "Una porta digitale semplice verso le attività del tuo club.",
    "howKicker": "Come funziona",
    "stepsTitle": "Tre passi per partire.",
    "stepActivate": "Attiva",
    "stepActivateText": "Registra la tua società e configura il tuo ambiente digitale.",
    "stepOrganize": "Organizza",
    "stepOrganizeText": "Gestisci tornei, giocatori, eventi e comunicazioni dalla tua area.",
    "stepGrow": "Cresci",
    "stepGrowText": "Offri ai tuoi giocatori un'esperienza più ordinata, moderna e coinvolgente.",
    "audienceKicker": "Per chi è Next Point Padel",
    "audienceTitle": "Pensato per chi vive il padel ogni giorno.",
    "clubs": "Società e club",
    "clubsText": "Per strutture che vogliono centralizzare la gestione e offrire un servizio digitale professionale.",
    "organizers": "Organizzatori e giocatori",
    "organizersText": "Per chi organizza competizioni e per chi vuole vivere tornei, eventi e attività del club in modo semplice.",
    "findKicker": "Sei già un giocatore?",
    "findTitle": "Trova la tua società.",
    "findText": "Cerca il tuo club su Next Point Padel e accedi alla sua pagina pubblica, ai tornei, agli eventi e ai servizi disponibili.",
    "searchPlaceholder": "Cerca società o club...",
    "searchButton": "CERCA SOCIETÀ",
    "loadingCompanies": "Caricamento delle società...",
    "ctaTitle": "Il prossimo punto è il tuo.",
    "ctaText": "Porta il tuo club su Next Point Padel e costruisci un'esperienza digitale più moderna per la tua società e per i tuoi giocatori.",
    "contactUs": "PARLA CON NOI",
    "info": "Informazioni",
    "contacts": "Contatti",
    "privacy": "Privacy",
    "cookie": "Cookie",
    "terms": "Termini"
  },
  "en": {
    "pageTitle": "Next Point Padel — The digital platform for your club",
    "navPlatform": "Platform",
    "navHow": "How it works",
    "navSociety": "Clubs",
    "activate": "ACTIVATE YOUR CLUB",
    "heroEyebrow": "The digital platform for padel",
    "heroTitle": "Your club.<br>A new digital experience.",
    "heroLead": "Next Point Padel helps clubs manage tournaments, players, events and communication in one professional environment.",
    "discover": "DISCOVER THE PLATFORM",
    "heroNote": "Designed for clubs, facilities and padel organizers.",
    "introKicker": "More control. Less work.",
    "introTitle": "The club you want to manage, all in one place.",
    "introText": "A platform designed to simplify daily management and give your players a modern digital experience. Tournaments, results, events and communications belong to the same ecosystem.",
    "featureTournaments": "Tournaments",
    "featureTournamentsText": "Organize formats, groups, brackets, results and standings.",
    "featurePlayers": "Players",
    "featurePlayersText": "Manage registrations, participants and access to the club environment.",
    "featureNews": "Events & News",
    "featureNewsText": "Share initiatives, appointments and content directly with your users.",
    "featureIdentity": "Club identity",
    "featureIdentityText": "A digital space built around your club and your audience.",
    "darkKicker": "From chaos to organization",
    "darkTitle": "Fewer separate tools. More time for your club.",
    "darkText": "Spreadsheets, messages, registrations, results and communications should not live in different places. Next Point Padel brings the club's main activities together in one coordinated, easy-to-use experience.",
    "seeHow": "SEE HOW IT WORKS",
    "solutionKicker": "What you can do",
    "solutionTitle": "A platform built for the club.",
    "solutionText": "Not just a list of features: a digital environment that supports the club from internal management to the player experience.",
    "management": "Management",
    "organizeTournaments": "Organize tournaments",
    "organizeTournamentsText": "Create and manage competitions, formats, teams, matches, results and standings.",
    "communication": "Communication",
    "beVisible": "Get noticed",
    "beVisibleText": "News, events and content help the club keep an active relationship with its players.",
    "experience": "Experience",
    "engagePlayers": "Engage players",
    "engagePlayersText": "A simple digital gateway to discover tournaments, activities, results and club services.",
    "showcaseKicker": "An ecosystem, not just management software",
    "showcaseTitle": "Technology works behind the scenes. The club stays in the spotlight.",
    "showcaseTournaments": "Tournaments and competitions",
    "showcaseTournamentsText": "From creating a competition to managing results and brackets.",
    "showcaseCommunication": "Club communication",
    "showcaseCommunicationText": "News, events and content in an environment consistent with the club.",
    "showcaseAccess": "Player access",
    "showcaseAccessText": "A simple digital gateway to your club's activities.",
    "howKicker": "How it works",
    "stepsTitle": "Three steps to get started.",
    "stepActivate": "Activate",
    "stepActivateText": "Register your club and configure your digital environment.",
    "stepOrganize": "Organize",
    "stepOrganizeText": "Manage tournaments, players, events and communications from your area.",
    "stepGrow": "Grow",
    "stepGrowText": "Give your players a more organized, modern and engaging experience.",
    "audienceKicker": "Who is Next Point Padel for?",
    "audienceTitle": "Designed for everyone who lives padel every day.",
    "clubs": "Clubs and facilities",
    "clubsText": "For clubs that want to centralize management and offer a professional digital service.",
    "organizers": "Organizers and players",
    "organizersText": "For those who organize competitions and those who want to experience tournaments, events and club activities simply.",
    "findKicker": "Already a player?",
    "findTitle": "Find your club.",
    "findText": "Search for your club on Next Point Padel and access its public page, tournaments, events and available services.",
    "searchPlaceholder": "Search for a club...",
    "searchButton": "SEARCH CLUBS",
    "loadingCompanies": "Loading clubs...",
    "ctaTitle": "The next point is yours.",
    "ctaText": "Bring your club to Next Point Padel and build a more modern digital experience for your club and players.",
    "contactUs": "TALK TO US",
    "info": "Information",
    "contacts": "Contact",
    "privacy": "Privacy",
    "cookie": "Cookies",
    "terms": "Terms"
  },
  "fr": {
    "pageTitle": "Next Point Padel — La plateforme numérique de votre club",
    "navPlatform": "Plateforme",
    "navHow": "Comment ça marche",
    "navSociety": "Clubs",
    "activate": "ACTIVEZ VOTRE CLUB",
    "heroEyebrow": "La plateforme numérique pour le padel",
    "heroTitle": "Votre club.<br>Une nouvelle expérience numérique.",
    "heroLead": "Next Point Padel aide les clubs à gérer tournois, joueurs, événements et communication dans un environnement professionnel unique.",
    "discover": "DÉCOUVRIR LA PLATEFORME",
    "heroNote": "Conçue pour les clubs, centres et organisateurs de padel.",
    "introKicker": "Plus de contrôle. Moins de travail.",
    "introTitle": "Le club que vous voulez gérer, en un seul endroit.",
    "introText": "Une plateforme conçue pour simplifier la gestion quotidienne et offrir à vos joueurs une expérience numérique moderne. Tournois, résultats, événements et communications font partie du même écosystème.",
    "featureTournaments": "Tournois",
    "featureTournamentsText": "Organisez les formats, groupes, tableaux, résultats et classements.",
    "featurePlayers": "Joueurs",
    "featurePlayersText": "Gérez les inscriptions, participants et accès à l'environnement du club.",
    "featureNews": "Événements & Actualités",
    "featureNewsText": "Partagez initiatives, rendez-vous et contenus directement avec vos utilisateurs.",
    "featureIdentity": "Identité du club",
    "featureIdentityText": "Un espace numérique construit autour de votre club et de votre public.",
    "darkKicker": "Du chaos à l'organisation",
    "darkTitle": "Moins d'outils séparés. Plus de temps pour votre club.",
    "darkText": "Tableurs, messages, inscriptions, résultats et communications ne doivent pas être dispersés. Next Point Padel réunit les principales activités du club dans une expérience coordonnée et simple.",
    "seeHow": "VOIR COMMENT ÇA MARCHE",
    "solutionKicker": "Ce que vous pouvez faire",
    "solutionTitle": "Une plateforme conçue pour le club.",
    "solutionText": "Pas une simple liste de fonctions : un environnement numérique qui accompagne le club de la gestion interne à l'expérience du joueur.",
    "management": "Gestion",
    "organizeTournaments": "Organisez les tournois",
    "organizeTournamentsText": "Créez et gérez compétitions, formats, équipes, matchs, résultats et classements.",
    "communication": "Communication",
    "beVisible": "Soyez visible",
    "beVisibleText": "Les actualités, événements et contenus aident le club à maintenir une relation active avec ses joueurs.",
    "experience": "Expérience",
    "engagePlayers": "Impliquez les joueurs",
    "engagePlayersText": "Un accès numérique simple pour découvrir tournois, activités, résultats et services du club.",
    "showcaseKicker": "Un écosystème, pas un simple logiciel de gestion",
    "showcaseTitle": "La technologie travaille en coulisses. Le club reste au premier plan.",
    "showcaseTournaments": "Tournois et compétitions",
    "showcaseTournamentsText": "De la création de la compétition à la gestion des résultats et du tableau.",
    "showcaseCommunication": "Communication du club",
    "showcaseCommunicationText": "Actualités, événements et contenus dans un environnement cohérent avec le club.",
    "showcaseAccess": "Accès pour les joueurs",
    "showcaseAccessText": "Une porte numérique simple vers les activités de votre club.",
    "howKicker": "Comment ça marche",
    "stepsTitle": "Trois étapes pour commencer.",
    "stepActivate": "Activez",
    "stepActivateText": "Enregistrez votre club et configurez votre environnement numérique.",
    "stepOrganize": "Organisez",
    "stepOrganizeText": "Gérez tournois, joueurs, événements et communications depuis votre espace.",
    "stepGrow": "Développez-vous",
    "stepGrowText": "Offrez à vos joueurs une expérience plus organisée, moderne et engageante.",
    "audienceKicker": "Pour qui est Next Point Padel ?",
    "audienceTitle": "Pensé pour ceux qui vivent le padel au quotidien.",
    "clubs": "Clubs et centres",
    "clubsText": "Pour les clubs qui veulent centraliser leur gestion et offrir un service numérique professionnel.",
    "organizers": "Organisateurs et joueurs",
    "organizersText": "Pour ceux qui organisent des compétitions et ceux qui veulent vivre simplement les tournois, événements et activités du club.",
    "findKicker": "Vous êtes déjà joueur ?",
    "findTitle": "Trouvez votre club.",
    "findText": "Recherchez votre club sur Next Point Padel et accédez à sa page publique, aux tournois, événements et services disponibles.",
    "searchPlaceholder": "Rechercher un club...",
    "searchButton": "RECHERCHER UN CLUB",
    "loadingCompanies": "Chargement des clubs...",
    "ctaTitle": "Le prochain point est à vous.",
    "ctaText": "Amenez votre club sur Next Point Padel et construisez une expérience numérique plus moderne pour votre club et vos joueurs.",
    "contactUs": "PARLEZ-NOUS",
    "info": "Informations",
    "contacts": "Contact",
    "privacy": "Confidentialité",
    "cookie": "Cookies",
    "terms": "Conditions"
  },
  "es": {
    "pageTitle": "Next Point Padel — La plataforma digital para tu club",
    "navPlatform": "Plataforma",
    "navHow": "Cómo funciona",
    "navSociety": "Clubes",
    "activate": "ACTIVA TU CLUB",
    "heroEyebrow": "La plataforma digital para el pádel",
    "heroTitle": "Tu club.<br>Una nueva experiencia digital.",
    "heroLead": "Next Point Padel ayuda a los clubes a gestionar torneos, jugadores, eventos y comunicación en un único entorno profesional.",
    "discover": "DESCUBRE LA PLATAFORMA",
    "heroNote": "Pensada para clubes, centros y organizadores de pádel.",
    "introKicker": "Más control. Menos trabajo.",
    "introTitle": "El club que quieres gestionar, en un solo lugar.",
    "introText": "Una plataforma diseñada para simplificar la gestión diaria y ofrecer a tus jugadores una experiencia digital moderna. Torneos, resultados, eventos y comunicaciones forman parte del mismo ecosistema.",
    "featureTournaments": "Torneos",
    "featureTournamentsText": "Organiza formatos, grupos, cuadros, resultados y clasificaciones.",
    "featurePlayers": "Jugadores",
    "featurePlayersText": "Gestiona inscripciones, participantes y accesos al entorno del club.",
    "featureNews": "Eventos y noticias",
    "featureNewsText": "Comparte iniciativas, citas y contenidos directamente con tus usuarios.",
    "featureIdentity": "Identidad del club",
    "featureIdentityText": "Un espacio digital construido alrededor de tu club y tu público.",
    "darkKicker": "Del caos a la organización",
    "darkTitle": "Menos herramientas separadas. Más tiempo para tu club.",
    "darkText": "Hojas de cálculo, mensajes, inscripciones, resultados y comunicaciones no tienen que estar en lugares distintos. Next Point Padel reúne las principales actividades del club en una experiencia coordinada y sencilla.",
    "seeHow": "VER CÓMO FUNCIONA",
    "solutionKicker": "Lo que puedes hacer",
    "solutionTitle": "Una plataforma creada para el club.",
    "solutionText": "No es solo una lista de funciones: es un entorno digital que acompaña al club desde la gestión interna hasta la experiencia del jugador.",
    "management": "Gestión",
    "organizeTournaments": "Organiza los torneos",
    "organizeTournamentsText": "Crea y gestiona competiciones, formatos, equipos, partidos, resultados y clasificaciones.",
    "communication": "Comunicación",
    "beVisible": "Hazte visible",
    "beVisibleText": "Noticias, eventos y contenidos ayudan al club a mantener una relación activa con sus jugadores.",
    "experience": "Experiencia",
    "engagePlayers": "Involucra a los jugadores",
    "engagePlayersText": "Un acceso digital sencillo para descubrir torneos, actividades, resultados y servicios del club.",
    "showcaseKicker": "Un ecosistema, no solo un software de gestión",
    "showcaseTitle": "La tecnología trabaja entre bastidores. El club sigue siendo protagonista.",
    "showcaseTournaments": "Torneos y competiciones",
    "showcaseTournamentsText": "Desde la creación de la competición hasta la gestión de resultados y cuadros.",
    "showcaseCommunication": "Comunicación del club",
    "showcaseCommunicationText": "Noticias, eventos y contenidos en un entorno coherente con el club.",
    "showcaseAccess": "Acceso para jugadores",
    "showcaseAccessText": "Una puerta digital sencilla a las actividades de tu club.",
    "howKicker": "Cómo funciona",
    "stepsTitle": "Tres pasos para empezar.",
    "stepActivate": "Activa",
    "stepActivateText": "Registra tu club y configura tu entorno digital.",
    "stepOrganize": "Organiza",
    "stepOrganizeText": "Gestiona torneos, jugadores, eventos y comunicaciones desde tu área.",
    "stepGrow": "Crece",
    "stepGrowText": "Ofrece a tus jugadores una experiencia más organizada, moderna y atractiva.",
    "audienceKicker": "¿Para quién es Next Point Padel?",
    "audienceTitle": "Pensado para quienes viven el pádel cada día.",
    "clubs": "Clubes y centros",
    "clubsText": "Para clubes que quieren centralizar la gestión y ofrecer un servicio digital profesional.",
    "organizers": "Organizadores y jugadores",
    "organizersText": "Para quienes organizan competiciones y quienes quieren vivir torneos, eventos y actividades del club de forma sencilla.",
    "findKicker": "¿Ya eres jugador?",
    "findTitle": "Encuentra tu club.",
    "findText": "Busca tu club en Next Point Padel y accede a su página pública, torneos, eventos y servicios disponibles.",
    "searchPlaceholder": "Buscar un club...",
    "searchButton": "BUSCAR CLUB",
    "loadingCompanies": "Cargando clubes...",
    "ctaTitle": "El próximo punto es tuyo.",
    "ctaText": "Lleva tu club a Next Point Padel y crea una experiencia digital más moderna para tu club y tus jugadores.",
    "contactUs": "HABLA CON NOSOTROS",
    "info": "Información",
    "contacts": "Contacto",
    "privacy": "Privacidad",
    "cookie": "Cookies",
    "terms": "Términos"
  },
  "de": {
    "pageTitle": "Next Point Padel — Die digitale Plattform für Ihren Club",
    "navPlatform": "Plattform",
    "navHow": "So funktioniert es",
    "navSociety": "Clubs",
    "activate": "AKTIVIEREN SIE IHREN CLUB",
    "heroEyebrow": "Die digitale Plattform für Padel",
    "heroTitle": "Ihr Club.<br>Eine neue digitale Erfahrung.",
    "heroLead": "Next Point Padel unterstützt Clubs bei der Verwaltung von Turnieren, Spielern, Veranstaltungen und Kommunikation in einer professionellen Umgebung.",
    "discover": "PLATTFORM ENTDECKEN",
    "heroNote": "Für Clubs, Anlagen und Padel-Veranstalter entwickelt.",
    "introKicker": "Mehr Kontrolle. Weniger Arbeit.",
    "introTitle": "Der Club, den Sie verwalten möchten, an einem Ort.",
    "introText": "Eine Plattform, die die tägliche Verwaltung vereinfacht und Ihren Spielern ein modernes digitales Erlebnis bietet. Turniere, Ergebnisse, Veranstaltungen und Kommunikation gehören zum selben Ökosystem.",
    "featureTournaments": "Turniere",
    "featureTournamentsText": "Organisieren Sie Formate, Gruppen, Turnierpläne, Ergebnisse und Ranglisten.",
    "featurePlayers": "Spieler",
    "featurePlayersText": "Verwalten Sie Anmeldungen, Teilnehmer und Zugänge zur Clubumgebung.",
    "featureNews": "Events & News",
    "featureNewsText": "Teilen Sie Aktionen, Termine und Inhalte direkt mit Ihren Nutzern.",
    "featureIdentity": "Club-Identität",
    "featureIdentityText": "Ein digitaler Raum rund um Ihren Club und Ihr Publikum.",
    "darkKicker": "Vom Chaos zur Organisation",
    "darkTitle": "Weniger getrennte Tools. Mehr Zeit für Ihren Club.",
    "darkText": "Tabellen, Nachrichten, Anmeldungen, Ergebnisse und Kommunikation müssen nicht an verschiedenen Orten liegen. Next Point Padel bündelt die wichtigsten Clubaktivitäten in einer koordinierten und einfachen Umgebung.",
    "seeHow": "SO FUNKTIONIERT ES",
    "solutionKicker": "Was Sie tun können",
    "solutionTitle": "Eine Plattform für den Club.",
    "solutionText": "Nicht nur eine Funktionsliste: eine digitale Umgebung, die den Club von der internen Verwaltung bis zum Spielerlebnis begleitet.",
    "management": "Verwaltung",
    "organizeTournaments": "Turniere organisieren",
    "organizeTournamentsText": "Erstellen und verwalten Sie Wettbewerbe, Formate, Teams, Spiele, Ergebnisse und Ranglisten.",
    "communication": "Kommunikation",
    "beVisible": "Werden Sie sichtbar",
    "beVisibleText": "News, Veranstaltungen und Inhalte helfen dem Club, die Beziehung zu seinen Spielern aktiv zu halten.",
    "experience": "Erlebnis",
    "engagePlayers": "Spieler einbinden",
    "engagePlayersText": "Ein einfacher digitaler Zugang zu Turnieren, Aktivitäten, Ergebnissen und Clubservices.",
    "showcaseKicker": "Ein Ökosystem, nicht nur Verwaltungssoftware",
    "showcaseTitle": "Die Technologie arbeitet im Hintergrund. Der Club bleibt im Mittelpunkt.",
    "showcaseTournaments": "Turniere und Wettbewerbe",
    "showcaseTournamentsText": "Von der Erstellung des Wettbewerbs bis zur Verwaltung von Ergebnissen und Turnierplan.",
    "showcaseCommunication": "Club-Kommunikation",
    "showcaseCommunicationText": "News, Veranstaltungen und Inhalte in einer Umgebung, die zum Club passt.",
    "showcaseAccess": "Spielerzugang",
    "showcaseAccessText": "Ein einfacher digitaler Zugang zu den Aktivitäten Ihres Clubs.",
    "howKicker": "So funktioniert es",
    "stepsTitle": "Drei Schritte zum Start.",
    "stepActivate": "Aktivieren",
    "stepActivateText": "Registrieren Sie Ihren Club und konfigurieren Sie Ihre digitale Umgebung.",
    "stepOrganize": "Organisieren",
    "stepOrganizeText": "Verwalten Sie Turniere, Spieler, Veranstaltungen und Kommunikation in Ihrem Bereich.",
    "stepGrow": "Wachsen",
    "stepGrowText": "Bieten Sie Ihren Spielern ein organisierteres, modernes und ansprechendes Erlebnis.",
    "audienceKicker": "Für wen ist Next Point Padel?",
    "audienceTitle": "Für alle, die jeden Tag Padel leben.",
    "clubs": "Clubs und Anlagen",
    "clubsText": "Für Clubs, die ihre Verwaltung zentralisieren und einen professionellen digitalen Service anbieten möchten.",
    "organizers": "Veranstalter und Spieler",
    "organizersText": "Für diejenigen, die Wettbewerbe organisieren, und für alle, die Turniere, Veranstaltungen und Clubaktivitäten einfach erleben möchten.",
    "findKicker": "Schon Spieler?",
    "findTitle": "Finden Sie Ihren Club.",
    "findText": "Suchen Sie Ihren Club auf Next Point Padel und greifen Sie auf seine öffentliche Seite, Turniere, Veranstaltungen und verfügbaren Services zu.",
    "searchPlaceholder": "Club suchen...",
    "searchButton": "CLUBS SUCHEN",
    "loadingCompanies": "Clubs werden geladen...",
    "ctaTitle": "Der nächste Punkt gehört Ihnen.",
    "ctaText": "Bringen Sie Ihren Club zu Next Point Padel und schaffen Sie ein moderneres digitales Erlebnis für Ihren Club und Ihre Spieler.",
    "contactUs": "SPRECHEN SIE MIT UNS",
    "info": "Informationen",
    "contacts": "Kontakt",
    "privacy": "Datenschutz",
    "cookie": "Cookies",
    "terms": "Bedingungen"
  }
};
  function current(){return localStorage.getItem(STORAGE_KEY)||"it";}
  function getText(key){const lang=current();const dict=Object.assign({},TEXT[lang]||{},LANDING_TEXT[lang]||{});return dict[key]!==undefined?dict[key]:(TEXT.it[key]!==undefined?TEXT.it[key]:(LANDING_TEXT.it[key]!==undefined?LANDING_TEXT.it[key]:key));}
  function flagHtml(lang){const item=LANGS[lang]||LANGS.it;return '<img class="language-flag" src="https://flagcdn.com/w20/'+item.flagCode+'.png" alt="" width="20" height="15" style="width:20px;height:15px;object-fit:cover;border-radius:2px;display:inline-block;vertical-align:-3px;flex:none">';}
  function setLanguage(lang){
    if(!LANGS[lang]) lang="it";
    localStorage.setItem(STORAGE_KEY,lang);
    document.documentElement.lang=lang;
    document.documentElement.dir=LANGS[lang].dir;
    const dict=Object.assign({},TEXT[lang]||{},LANDING_TEXT[lang]||{});document.querySelectorAll("[data-i18n]").forEach(el=>{const key=el.dataset.i18n;if(dict[key]!==undefined)el.innerHTML=dict[key];});
    document.querySelectorAll("[data-i18n-placeholder]").forEach(el=>{const key=el.dataset.i18nPlaceholder;if(TEXT[lang][key]!==undefined)el.placeholder=TEXT[lang][key];});
    const selector=document.getElementById("languageSelector");
    if(selector){
      const active=LANGS[lang];
      const currentLabel=selector.querySelector(".language-current");
      if(currentLabel)currentLabel.innerHTML=flagHtml(lang)+" <span>"+active.short+"</span><b>▾</b>";
      selector.querySelectorAll("[data-lang]").forEach(item=>{
        const itemLang=item.dataset.lang;
        if(LANGS[itemLang]){
          item.innerHTML=flagHtml(itemLang)+" <span>"+LANGS[itemLang].name+"</span>";
          item.classList.toggle("active",itemLang===lang);
        }
      });
    }
    document.dispatchEvent(new CustomEvent("nextpointlanguagechange",{detail:{language:lang}}));
  }
  function init(){
    const selector=document.getElementById("languageSelector");
    if(selector){
      const button=selector.querySelector(".language-button");
      button.addEventListener("click",function(e){e.stopPropagation();selector.classList.toggle("open");});
      selector.querySelectorAll("[data-lang]").forEach(item=>item.addEventListener("click",function(){setLanguage(item.dataset.lang);selector.classList.remove("open");}));
      document.addEventListener("click",function(){selector.classList.remove("open");});
    }
    setLanguage(current());
  }
  window.NextPointLanguage={setLanguage,getText,current,LANGS,TEXT};
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",init);else init();
})();